
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Table table1;

	private global::Gtk.ToggleButton togglebutton10;

	private global::Gtk.ToggleButton togglebutton11;

	private global::Gtk.ToggleButton togglebutton12;

	private global::Gtk.ToggleButton togglebutton13;

	private global::Gtk.ToggleButton togglebutton14;

	private global::Gtk.ToggleButton togglebutton15;

	private global::Gtk.ToggleButton togglebutton16;

	private global::Gtk.ToggleButton togglebutton17;

	private global::Gtk.ToggleButton togglebutton18;

	private global::Gtk.ToggleButton togglebutton19;

	private global::Gtk.ToggleButton togglebutton2;

	private global::Gtk.ToggleButton togglebutton20;

	private global::Gtk.ToggleButton togglebutton21;

	private global::Gtk.ToggleButton togglebutton3;

	private global::Gtk.ToggleButton togglebutton4;

	private global::Gtk.ToggleButton togglebutton5;

	private global::Gtk.ToggleButton togglebutton6;

	private global::Gtk.ToggleButton togglebutton7;

	private global::Gtk.ToggleButton togglebutton8;

	private global::Gtk.ToggleButton togglebutton9;

	private global::Gtk.Label label1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.table1 = new global::Gtk.Table(((uint)(5)), ((uint)(4)), false);
		this.table1.Name = "table1";
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton10 = new global::Gtk.ToggleButton();
		this.togglebutton10.CanFocus = true;
		this.togglebutton10.Name = "togglebutton10";
		this.togglebutton10.UseUnderline = true;
		this.togglebutton10.Active = true;
		this.togglebutton10.Label = global::Mono.Unix.Catalog.GetString("4");
		this.table1.Add(this.togglebutton10);
		global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton10]));
		w1.TopAttach = ((uint)(2));
		w1.BottomAttach = ((uint)(3));
		w1.XOptions = ((global::Gtk.AttachOptions)(4));
		w1.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton11 = new global::Gtk.ToggleButton();
		this.togglebutton11.HeightRequest = 0;
		this.togglebutton11.CanFocus = true;
		this.togglebutton11.Name = "togglebutton11";
		this.togglebutton11.UseUnderline = true;
		this.togglebutton11.Active = true;
		this.togglebutton11.Label = global::Mono.Unix.Catalog.GetString("5");
		this.table1.Add(this.togglebutton11);
		global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton11]));
		w2.TopAttach = ((uint)(2));
		w2.BottomAttach = ((uint)(3));
		w2.LeftAttach = ((uint)(1));
		w2.RightAttach = ((uint)(2));
		w2.XOptions = ((global::Gtk.AttachOptions)(4));
		w2.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton12 = new global::Gtk.ToggleButton();
		this.togglebutton12.WidthRequest = 90;
		this.togglebutton12.HeightRequest = 90;
		this.togglebutton12.CanFocus = true;
		this.togglebutton12.Name = "togglebutton12";
		this.togglebutton12.UseUnderline = true;
		this.togglebutton12.Active = true;
		this.togglebutton12.Label = global::Mono.Unix.Catalog.GetString("6");
		this.table1.Add(this.togglebutton12);
		global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton12]));
		w3.TopAttach = ((uint)(2));
		w3.BottomAttach = ((uint)(3));
		w3.LeftAttach = ((uint)(2));
		w3.RightAttach = ((uint)(3));
		w3.XOptions = ((global::Gtk.AttachOptions)(4));
		w3.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton13 = new global::Gtk.ToggleButton();
		this.togglebutton13.CanFocus = true;
		this.togglebutton13.Name = "togglebutton13";
		this.togglebutton13.UseUnderline = true;
		this.togglebutton13.Active = true;
		this.togglebutton13.Label = global::Mono.Unix.Catalog.GetString("+");
		this.table1.Add(this.togglebutton13);
		global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton13]));
		w4.TopAttach = ((uint)(2));
		w4.BottomAttach = ((uint)(3));
		w4.LeftAttach = ((uint)(3));
		w4.RightAttach = ((uint)(4));
		w4.XOptions = ((global::Gtk.AttachOptions)(4));
		w4.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton14 = new global::Gtk.ToggleButton();
		this.togglebutton14.CanFocus = true;
		this.togglebutton14.Name = "togglebutton14";
		this.togglebutton14.UseUnderline = true;
		this.togglebutton14.Active = true;
		this.togglebutton14.Label = global::Mono.Unix.Catalog.GetString("(    )");
		this.table1.Add(this.togglebutton14);
		global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton14]));
		w5.TopAttach = ((uint)(3));
		w5.BottomAttach = ((uint)(4));
		w5.LeftAttach = ((uint)(3));
		w5.RightAttach = ((uint)(4));
		w5.XOptions = ((global::Gtk.AttachOptions)(4));
		w5.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton15 = new global::Gtk.ToggleButton();
		this.togglebutton15.WidthRequest = 90;
		this.togglebutton15.HeightRequest = 90;
		this.togglebutton15.CanFocus = true;
		this.togglebutton15.Name = "togglebutton15";
		this.togglebutton15.UseUnderline = true;
		this.togglebutton15.Active = true;
		this.togglebutton15.Label = global::Mono.Unix.Catalog.GetString("=");
		this.table1.Add(this.togglebutton15);
		global::Gtk.Table.TableChild w6 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton15]));
		w6.TopAttach = ((uint)(4));
		w6.BottomAttach = ((uint)(5));
		w6.LeftAttach = ((uint)(3));
		w6.RightAttach = ((uint)(4));
		w6.XOptions = ((global::Gtk.AttachOptions)(4));
		w6.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton16 = new global::Gtk.ToggleButton();
		this.togglebutton16.CanFocus = true;
		this.togglebutton16.Name = "togglebutton16";
		this.togglebutton16.UseUnderline = true;
		this.togglebutton16.Label = global::Mono.Unix.Catalog.GetString("<-");
		this.table1.Add(this.togglebutton16);
		global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton16]));
		w7.TopAttach = ((uint)(4));
		w7.BottomAttach = ((uint)(5));
		w7.LeftAttach = ((uint)(2));
		w7.RightAttach = ((uint)(3));
		w7.XOptions = ((global::Gtk.AttachOptions)(4));
		w7.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton17 = new global::Gtk.ToggleButton();
		this.togglebutton17.WidthRequest = 90;
		this.togglebutton17.HeightRequest = 90;
		this.togglebutton17.CanFocus = true;
		this.togglebutton17.Name = "togglebutton17";
		this.togglebutton17.UseUnderline = true;
		this.togglebutton17.Active = true;
		this.togglebutton17.Label = global::Mono.Unix.Catalog.GetString("9");
		this.table1.Add(this.togglebutton17);
		global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton17]));
		w8.TopAttach = ((uint)(3));
		w8.BottomAttach = ((uint)(4));
		w8.LeftAttach = ((uint)(2));
		w8.RightAttach = ((uint)(3));
		w8.XOptions = ((global::Gtk.AttachOptions)(4));
		w8.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton18 = new global::Gtk.ToggleButton();
		this.togglebutton18.CanFocus = true;
		this.togglebutton18.Name = "togglebutton18";
		this.togglebutton18.UseUnderline = true;
		this.togglebutton18.Active = true;
		this.togglebutton18.Label = global::Mono.Unix.Catalog.GetString("8");
		this.table1.Add(this.togglebutton18);
		global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton18]));
		w9.TopAttach = ((uint)(3));
		w9.BottomAttach = ((uint)(4));
		w9.LeftAttach = ((uint)(1));
		w9.RightAttach = ((uint)(2));
		w9.XOptions = ((global::Gtk.AttachOptions)(4));
		w9.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton19 = new global::Gtk.ToggleButton();
		this.togglebutton19.CanFocus = true;
		this.togglebutton19.Name = "togglebutton19";
		this.togglebutton19.UseUnderline = true;
		this.togglebutton19.Active = true;
		this.togglebutton19.Label = global::Mono.Unix.Catalog.GetString("0");
		this.table1.Add(this.togglebutton19);
		global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton19]));
		w10.TopAttach = ((uint)(4));
		w10.BottomAttach = ((uint)(5));
		w10.LeftAttach = ((uint)(1));
		w10.RightAttach = ((uint)(2));
		w10.XOptions = ((global::Gtk.AttachOptions)(4));
		w10.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton2 = new global::Gtk.ToggleButton();
		this.togglebutton2.WidthRequest = 90;
		this.togglebutton2.HeightRequest = 90;
		this.togglebutton2.CanFocus = true;
		this.togglebutton2.Name = "togglebutton2";
		this.togglebutton2.UseUnderline = true;
		this.togglebutton2.Active = true;
		this.togglebutton2.Label = global::Mono.Unix.Catalog.GetString("C");
		this.table1.Add(this.togglebutton2);
		global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton2]));
		w11.XOptions = ((global::Gtk.AttachOptions)(3));
		w11.YOptions = ((global::Gtk.AttachOptions)(3));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton20 = new global::Gtk.ToggleButton();
		this.togglebutton20.CanFocus = true;
		this.togglebutton20.Name = "togglebutton20";
		this.togglebutton20.UseUnderline = true;
		this.togglebutton20.Active = true;
		this.togglebutton20.Label = global::Mono.Unix.Catalog.GetString(".");
		this.table1.Add(this.togglebutton20);
		global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton20]));
		w12.TopAttach = ((uint)(4));
		w12.BottomAttach = ((uint)(5));
		w12.XOptions = ((global::Gtk.AttachOptions)(4));
		w12.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton21 = new global::Gtk.ToggleButton();
		this.togglebutton21.CanFocus = true;
		this.togglebutton21.Name = "togglebutton21";
		this.togglebutton21.UseUnderline = true;
		this.togglebutton21.Active = true;
		this.togglebutton21.Label = global::Mono.Unix.Catalog.GetString("7");
		this.table1.Add(this.togglebutton21);
		global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton21]));
		w13.TopAttach = ((uint)(3));
		w13.BottomAttach = ((uint)(4));
		w13.XOptions = ((global::Gtk.AttachOptions)(4));
		w13.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton3 = new global::Gtk.ToggleButton();
		this.togglebutton3.CanFocus = true;
		this.togglebutton3.Name = "togglebutton3";
		this.togglebutton3.UseUnderline = true;
		this.togglebutton3.Label = global::Mono.Unix.Catalog.GetString("/");
		this.table1.Add(this.togglebutton3);
		global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton3]));
		w14.LeftAttach = ((uint)(1));
		w14.RightAttach = ((uint)(2));
		w14.XOptions = ((global::Gtk.AttachOptions)(4));
		w14.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton4 = new global::Gtk.ToggleButton();
		this.togglebutton4.CanFocus = true;
		this.togglebutton4.Name = "togglebutton4";
		this.togglebutton4.UseUnderline = true;
		this.togglebutton4.Active = true;
		this.togglebutton4.Label = global::Mono.Unix.Catalog.GetString("%");
		this.table1.Add(this.togglebutton4);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton4]));
		w15.LeftAttach = ((uint)(2));
		w15.RightAttach = ((uint)(3));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton5 = new global::Gtk.ToggleButton();
		this.togglebutton5.CanFocus = true;
		this.togglebutton5.Name = "togglebutton5";
		this.togglebutton5.UseUnderline = true;
		this.togglebutton5.Active = true;
		this.togglebutton5.Label = global::Mono.Unix.Catalog.GetString("X");
		this.table1.Add(this.togglebutton5);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton5]));
		w16.LeftAttach = ((uint)(3));
		w16.RightAttach = ((uint)(4));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton6 = new global::Gtk.ToggleButton();
		this.togglebutton6.CanFocus = true;
		this.togglebutton6.Name = "togglebutton6";
		this.togglebutton6.UseUnderline = true;
		this.togglebutton6.Active = true;
		this.togglebutton6.Label = global::Mono.Unix.Catalog.GetString("---");
		this.table1.Add(this.togglebutton6);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton6]));
		w17.TopAttach = ((uint)(1));
		w17.BottomAttach = ((uint)(2));
		w17.LeftAttach = ((uint)(3));
		w17.RightAttach = ((uint)(4));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton7 = new global::Gtk.ToggleButton();
		this.togglebutton7.CanFocus = true;
		this.togglebutton7.Name = "togglebutton7";
		this.togglebutton7.UseUnderline = true;
		this.togglebutton7.Active = true;
		this.togglebutton7.Label = global::Mono.Unix.Catalog.GetString("3");
		this.table1.Add(this.togglebutton7);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton7]));
		w18.TopAttach = ((uint)(1));
		w18.BottomAttach = ((uint)(2));
		w18.LeftAttach = ((uint)(2));
		w18.RightAttach = ((uint)(3));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton8 = new global::Gtk.ToggleButton();
		this.togglebutton8.WidthRequest = 90;
		this.togglebutton8.HeightRequest = 90;
		this.togglebutton8.CanFocus = true;
		this.togglebutton8.Name = "togglebutton8";
		this.togglebutton8.UseUnderline = true;
		this.togglebutton8.Active = true;
		this.togglebutton8.Label = global::Mono.Unix.Catalog.GetString("2");
		this.table1.Add(this.togglebutton8);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton8]));
		w19.TopAttach = ((uint)(1));
		w19.BottomAttach = ((uint)(2));
		w19.LeftAttach = ((uint)(1));
		w19.RightAttach = ((uint)(2));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.togglebutton9 = new global::Gtk.ToggleButton();
		this.togglebutton9.CanFocus = true;
		this.togglebutton9.Name = "togglebutton9";
		this.togglebutton9.UseUnderline = true;
		this.togglebutton9.Active = true;
		this.togglebutton9.Label = global::Mono.Unix.Catalog.GetString("1");
		this.table1.Add(this.togglebutton9);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1[this.togglebutton9]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		this.fixed1.Add(this.table1);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.table1]));
		w21.Y = 160;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label1 = new global::Gtk.Label();
		this.label1.WidthRequest = 360;
		this.label1.HeightRequest = 160;
		this.label1.Name = "label1";
		this.label1.Justify = ((global::Gtk.Justification)(1));
		this.fixed1.Add(this.label1);
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 361;
		this.DefaultHeight = 610;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.togglebutton9.Clicked += new global::System.EventHandler(this.OnTogglebutton9Clicked);
		this.togglebutton8.Clicked += new global::System.EventHandler(this.OnTogglebutton8Clicked);
		this.togglebutton7.Clicked += new global::System.EventHandler(this.OnTogglebutton7Clicked);
		this.togglebutton6.Clicked += new global::System.EventHandler(this.OnTogglebutton6Clicked);
		this.togglebutton5.Clicked += new global::System.EventHandler(this.OnTogglebutton5Clicked);
		this.togglebutton4.Clicked += new global::System.EventHandler(this.OnTogglebutton4Clicked);
		this.togglebutton3.Clicked += new global::System.EventHandler(this.OnTogglebutton3Clicked);
		this.togglebutton21.Clicked += new global::System.EventHandler(this.OnTogglebutton21Clicked);
		this.togglebutton20.Clicked += new global::System.EventHandler(this.OnTogglebutton20Clicked);
		this.togglebutton2.Clicked += new global::System.EventHandler(this.OnTogglebutton2Clicked);
		this.togglebutton19.Clicked += new global::System.EventHandler(this.OnTogglebutton19Clicked);
		this.togglebutton18.Clicked += new global::System.EventHandler(this.OnTogglebutton18Clicked);
		this.togglebutton17.Clicked += new global::System.EventHandler(this.OnTogglebutton17Clicked);
		this.togglebutton16.Clicked += new global::System.EventHandler(this.OnTogglebutton16Clicked);
		this.togglebutton15.Clicked += new global::System.EventHandler(this.OnTogglebutton15Clicked);
		this.togglebutton14.Clicked += new global::System.EventHandler(this.OnTogglebutton14Clicked);
		this.togglebutton13.Clicked += new global::System.EventHandler(this.OnTogglebutton13Clicked);
		this.togglebutton12.Clicked += new global::System.EventHandler(this.OnTogglebutton12Clicked);
		this.togglebutton11.Clicked += new global::System.EventHandler(this.OnTogglebutton11Clicked);
		this.togglebutton10.Clicked += new global::System.EventHandler(this.OnTogglebutton10Clicked);
	}
}
